"""Initial migration - emission models

Revision ID: 42a729e8af08
Revises:
Create Date: 2025-11-24 10:41:17.102422

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "42a729e8af08"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "air_travel_activities",
        sa.Column(
            "distance_miles",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Distance traveled in miles",
        ),
        sa.Column(
            "distance_km",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Distance traveled in kilometres (converted from miles)",
        ),
        sa.Column(
            "flight_range",
            sa.String(length=50),
            nullable=False,
            comment="Flight range category (e.g., Short-haul, Long-haul, International)",
        ),
        sa.Column(
            "passenger_class",
            sa.String(length=50),
            nullable=False,
            comment="Passenger class (e.g., Economy, Business, First)",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False, comment="Date when the activity occurred"),
        sa.Column(
            "activity_type", sa.String(length=100), nullable=False, comment="Type of activity"
        ),
        sa.Column(
            "source_file",
            sa.String(length=255),
            nullable=True,
            comment="Original CSV filename if imported from file",
        ),
        sa.Column(
            "raw_data", sa.JSON(), nullable=True, comment="Original CSV row data for audit trail"
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        comment="Air travel activity data (Scope 3, Category 6)",
    )
    op.create_index(
        op.f("ix_air_travel_activities_date"), "air_travel_activities", ["date"], unique=False
    )
    op.create_index(
        "ix_air_travel_activities_date_desc", "air_travel_activities", ["date"], unique=False
    )
    op.create_index(
        "ix_air_travel_activities_date_range",
        "air_travel_activities",
        ["date", "flight_range"],
        unique=False,
    )
    op.create_index(
        op.f("ix_air_travel_activities_flight_range"),
        "air_travel_activities",
        ["flight_range"],
        unique=False,
    )

    op.create_table(
        "electricity_activities",
        sa.Column(
            "country",
            sa.String(length=100),
            nullable=False,
            comment="Country where electricity was consumed",
        ),
        sa.Column(
            "usage_kwh",
            sa.Numeric(precision=12, scale=4),
            nullable=False,
            comment="Electricity consumption in kilowatt-hours",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False, comment="Date when the activity occurred"),
        sa.Column(
            "activity_type", sa.String(length=100), nullable=False, comment="Type of activity"
        ),
        sa.Column(
            "source_file",
            sa.String(length=255),
            nullable=True,
            comment="Original CSV filename if imported from file",
        ),
        sa.Column(
            "raw_data", sa.JSON(), nullable=True, comment="Original CSV row data for audit trail"
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        comment="Electricity consumption activity data (Scope 2)",
    )
    op.create_index(
        op.f("ix_electricity_activities_country"),
        "electricity_activities",
        ["country"],
        unique=False,
    )
    op.create_index(
        op.f("ix_electricity_activities_date"), "electricity_activities", ["date"], unique=False
    )
    op.create_index(
        "ix_electricity_activities_date_country",
        "electricity_activities",
        ["date", "country"],
        unique=False,
    )
    op.create_index(
        "ix_electricity_activities_date_desc", "electricity_activities", ["date"], unique=False
    )

    op.create_table(
        "emission_factors",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "activity_type",
            sa.String(length=100),
            nullable=False,
            comment="Type of activity this emission factor applies to",
        ),
        sa.Column(
            "lookup_identifier",
            sa.String(length=200),
            nullable=False,
            comment="Identifier used to match activity data (e.g., 'United Kingdom', 'Long-haul, Business class')",
        ),
        sa.Column(
            "unit",
            sa.String(length=50),
            nullable=False,
            comment="Unit of measurement (e.g., kWh, GBP, kilometres)",
        ),
        sa.Column(
            "co2e_factor",
            sa.Numeric(precision=10, scale=6),
            nullable=False,
            comment="CO2e emission factor value (kgCO2e per unit)",
        ),
        sa.Column("scope", sa.Integer(), nullable=False, comment="GHG Protocol scope (1, 2, or 3)"),
        sa.Column(
            "category",
            sa.Integer(),
            nullable=True,
            comment="GHG Protocol Scope 3 category number (for Scope 3 only)",
        ),
        sa.Column(
            "source",
            sa.String(length=200),
            nullable=True,
            comment="Source of the emission factor (e.g., 'DEFRA 2024', 'EPA 2023')",
        ),
        sa.Column(
            "notes",
            sa.String(),
            nullable=True,
            comment="Additional notes or context about this emission factor",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        comment="Emission factor lookup table for CO2e calculations",
    )
    op.create_index(
        "ix_emission_factors_activity_lookup",
        "emission_factors",
        ["activity_type", "lookup_identifier"],
        unique=False,
    )
    op.create_index(
        "ix_emission_factors_activity_scope",
        "emission_factors",
        ["activity_type", "scope"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emission_factors_activity_type"),
        "emission_factors",
        ["activity_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_emission_factors_lookup_identifier"),
        "emission_factors",
        ["lookup_identifier"],
        unique=False,
    )

    op.create_table(
        "goods_services_activities",
        sa.Column(
            "supplier_category",
            sa.String(length=200),
            nullable=False,
            comment="Industry or category of the supplier",
        ),
        sa.Column(
            "spend_gbp",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="Amount spent in GBP",
        ),
        sa.Column(
            "description",
            sa.String(),
            nullable=True,
            comment="Additional description of the purchase",
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False, comment="Date when the activity occurred"),
        sa.Column(
            "activity_type", sa.String(length=100), nullable=False, comment="Type of activity"
        ),
        sa.Column(
            "source_file",
            sa.String(length=255),
            nullable=True,
            comment="Original CSV filename if imported from file",
        ),
        sa.Column(
            "raw_data", sa.JSON(), nullable=True, comment="Original CSV row data for audit trail"
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        comment="Purchased goods and services activity data (Scope 3, Category 1)",
    )
    op.create_index(
        op.f("ix_goods_services_activities_date"),
        "goods_services_activities",
        ["date"],
        unique=False,
    )
    op.create_index(
        "ix_goods_services_activities_date_category",
        "goods_services_activities",
        ["date", "supplier_category"],
        unique=False,
    )
    op.create_index(
        "ix_goods_services_activities_date_desc",
        "goods_services_activities",
        ["date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_goods_services_activities_supplier_category"),
        "goods_services_activities",
        ["supplier_category"],
        unique=False,
    )

    op.create_table(
        "emission_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "activity_type",
            sa.String(length=100),
            nullable=False,
            comment="Type of activity data (Electricity, Air Travel, Purchased Goods and Services)",
        ),
        sa.Column(
            "activity_id", sa.UUID(), nullable=False, comment="ID of the specific activity record"
        ),
        sa.Column(
            "emission_factor_id",
            sa.UUID(),
            nullable=False,
            comment="Emission factor used in the calculation",
        ),
        sa.Column(
            "co2e_tonnes",
            sa.Numeric(precision=15, scale=7),
            nullable=False,
            comment="Calculated CO2e emissions in tonnes",
        ),
        sa.Column(
            "confidence_score",
            sa.Numeric(precision=3, scale=2),
            nullable=False,
            comment="Confidence score for emission factor matching (0.0 to 1.0)",
        ),
        sa.Column(
            "calculation_metadata",
            sa.JSON(),
            nullable=True,
            comment="Additional calculation details (method, intermediate values, etc.)",
        ),
        sa.Column(
            "calculation_date",
            sa.Date(),
            nullable=False,
            comment="Date when the emission was calculated",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["emission_factor_id"], ["emission_factors.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Calculated emission results linking activities to emission factors",
    )
    op.create_index(
        "ix_emission_results_activity",
        "emission_results",
        ["activity_type", "activity_id"],
        unique=False,
    )
    op.create_index(
        "ix_emission_results_calculation_date",
        "emission_results",
        ["calculation_date"],
        unique=False,
    )
    op.create_index(
        "ix_emission_results_created_desc", "emission_results", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_emission_results_created_desc", table_name="emission_results")
    op.drop_index("ix_emission_results_calculation_date", table_name="emission_results")
    op.drop_index("ix_emission_results_activity", table_name="emission_results")
    op.drop_table("emission_results")
    op.drop_index(
        op.f("ix_goods_services_activities_supplier_category"),
        table_name="goods_services_activities",
    )
    op.drop_index("ix_goods_services_activities_date_desc", table_name="goods_services_activities")
    op.drop_index(
        "ix_goods_services_activities_date_category", table_name="goods_services_activities"
    )
    op.drop_index(op.f("ix_goods_services_activities_date"), table_name="goods_services_activities")
    op.drop_table("goods_services_activities")
    op.drop_index(op.f("ix_emission_factors_lookup_identifier"), table_name="emission_factors")
    op.drop_index(op.f("ix_emission_factors_activity_type"), table_name="emission_factors")
    op.drop_index("ix_emission_factors_activity_scope", table_name="emission_factors")
    op.drop_index("ix_emission_factors_activity_lookup", table_name="emission_factors")
    op.drop_table("emission_factors")
    op.drop_index("ix_electricity_activities_date_desc", table_name="electricity_activities")
    op.drop_index("ix_electricity_activities_date_country", table_name="electricity_activities")
    op.drop_index(op.f("ix_electricity_activities_date"), table_name="electricity_activities")
    op.drop_index(op.f("ix_electricity_activities_country"), table_name="electricity_activities")
    op.drop_table("electricity_activities")
    op.drop_index(op.f("ix_air_travel_activities_flight_range"), table_name="air_travel_activities")
    op.drop_index("ix_air_travel_activities_date_range", table_name="air_travel_activities")
    op.drop_index("ix_air_travel_activities_date_desc", table_name="air_travel_activities")
    op.drop_index(op.f("ix_air_travel_activities_date"), table_name="air_travel_activities")
    op.drop_table("air_travel_activities")
    # ### end Alembic commands ###
